---
version: "3"

volumes:
  cache:
  system-cache:

services:
  librespot:
    image: ${IMAGE_REGISTRY:-docker.io}/giof71/librespot:${IMAGE_TAG:-latest}
    container_name: librespot-alsa
    user: "${uid:-0}:${gid:-0}"
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    environment:
      - PUID=${PUID:-}
      - PGID=${PGID:-}
      - AUDIO_GID=${AUDIO_GID:-}
      - DEVICE=${ALSA_DEVICE:-default}
      - FORMAT=${ALSA_FORMAT:-S16}
      - BACKEND=alsa
      - BITRATE=${BITRATE:-320}
      - INITIAL_VOLUME=${INITIAL_VOLUME:-100}
      - DEVICE_TYPE=${DEVICE_TYPE:-homething}
      - DEVICE_NAME=${DEVICE_NAME:-LibreSpot}
      - ENABLE_CACHE=${ENABLE_CACHE:-n}
      - ENABLE_SYSTEM_CACHE=${ENABLE_SYSTEM_CACHE:-n}
      - DISABLE_CREDENTIALS_CACHE=${DISABLE_CREDENTIALS_CACHE:-y}
    volumes:
      - cache:/data/cache
      - system-cache:/data/system-cache
    restart: unless-stopped
