---
version: "3"

services:
  squeezelite:
    image: ${DOCKER_REGISTRY:-docker.io}/giof71/squeezelite:${IMAGE_TAG:-latest}
    container_name: squeezelite-discovery
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    environment:
      - SQUEEZELITE_NAME=${SQUEEZELITE_NAME:-SqueezeLite}
      - SQUEEZELITE_AUDIO_DEVICE=${SQUEEZELITE_AUDIO_DEVICE:-default}
      - SQUEEZELITE_VOLUME_CONTROL=${SQUEEZELITE_VOLUME_CONTROL:-}
      - SQUEEZELITE_PARAMS=${SQUEEZELITE_PARAMS:-}
      - SQUEEZELITE_SERVER_PORT=${SQUEEZELITE_SERVER_PORT:-}
    volumes:
      - ./config:/config
    restart: always
