---
version: "3"

services:
  squeezelite:
    image: ${DOCKER_REPO:-docker.io}/giof71/squeezelite
    container_name: squeezelite-nodiscovery
    devices:
      - /dev/snd:/dev/snd
    environment:
      - SQUEEZELITE_NAME=${SQUEEZELITE_NAME:-SqueezeLite}
      - SQUEEZELITE_AUDIO_DEVICE=${SQUEEZELITE_AUDIO_DEVICE:-default}
      - SQUEEZELITE_SERVER_PORT=${SQUEEZELITE_SERVER_PORT}