---
version: "3"

services:
  squeezelite:
    image: ${DOCKER_REGISTRY:-docker.io}/giof71/squeezelite:${IMAGE_TAG:-latest}
    user: "${PUID:-1000}:${AUDIO_GID:-29}"
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    environment:
      - PRESET=archimago-goldilocks,rates_up_to_384k
      - SQUEEZELITE_EXCLUDE_CODECS=${SQUEEZELITE_EXCLUDE_CODECS:-}
      - SQUEEZELITE_NAME=${SQUEEZELITE_NAME:-SqueezeLite 8x}
      - SQUEEZELITE_AUDIO_DEVICE=${SQUEEZELITE_AUDIO_DEVICE:-default}
      - SQUEEZELITE_VOLUME_CONTROL=${SQUEEZELITE_VOLUME_CONTROL:-}
      - SQUEEZELITE_PARAMS=${SQUEEZELITE_PARAMS:-}
      - SQUEEZELITE_SERVER_PORT=${SQUEEZELITE_SERVER_PORT:-}
    volumes:
      - ./config:/config
    restart: unless-stopped
