---
version: "3.3"

services:
  mopidy:
    image: ${MOPIDY_IMAGE_REPO:-docker.io}/giof71/mopidy:${MOPIDY_IMAGE_TAG:-latest}
    container_name: mopidy-tidal
    user: "${PUID}:${AUDIO_GID}"
    devices:
      - /dev/snd:/dev/snd
    environment:
      - AUDIO_OUTPUT=${AUDIO_OUTPUT:-autoaudiosink}
      - TIDAL_ENABLED=${TIDAL_ENABLED:-yes}
      - TIDAL_QUALITY=${TIDAL_QUALITY:-LOSSLESS}
      - TIDAL_AUTH_METHOD=${TIDAL_AUTH_METHOD:-OAUTH}
      - TIDAL_LOGIN_SERVER_PORT=${TIDAL_LOGIN_SERVER_PORT:-8989}
      - MPD_ENABLED=yes
    ports:
      - ${MOPIDY_PORT:-6680}:6680
      - ${TIDAL_LOGIN_SERVER_PORT:-8989}:${TIDAL_LOGIN_SERVER_PORT:-8989}
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./data:/data
      - ./dconf:/.cache/dconf
    restart: unless-stopped

  yams:
    image: ${YAMS_IMAGE_REPO:-docker.io}/giof71/yams:latest
    container_name: mopidy-yams
    depends_on:
      - mopidy
    environment:
      - TZ=Europe/Rome
      - MPD_HOST=mopidy
      - MPD_PORT=6600
    volumes:
      - ./yams:/data
    restart: unless-stopped
