---
version: '3.3'

volumes:
  mpd-db:
  upmpdcli-cache:
  upmpdcli-confdir:
  yams-data:

services:
  mpd:
    image: ${DOCKER_REGISTRY:-docker.io}/giof71/mpd-alsa:${MPD_TAG:-vanilla}
    container_name: upnp-renderer-simple-mpd
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    environment:
      - MPD_BIND_ADDRESS=${MPD_BIND_ADDRESS:-127.0.0.1}
      - MPD_PORT=${MPD_PORT:-6600}
      - USER_MODE=N
      - ALSA_OUTPUT_CREATE=yes
      - ALSA_OUTPUT_ENABLED=yes
      - ALSA_OUTPUT_DEVICE=${MPD_ALSA_DEVICE:-default}
      - ALSA_OUTPUT_MIXER_TYPE=${MPD_MIXER_TYPE:-software}
      - ALSA_OUTPUT_FORMAT=${MPD_ALSA_OUTPUT_FORMAT:-}
    volumes:
      - mpd-db:/db
    restart: unless-stopped

  upmpdcli:
    image: ${DOCKER_REGISTRY:-docker.io}/giof71/upmpdcli:${UPMPDCLI_TAG:-latest-renderer}
    container_name: upnp-renderer-simple-upmpdcli
    network_mode: host
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - MPD_HOST=${MPD_HOST:-127.0.0.1}
      - MPD_PORT=${MPD_PORT:-6600}
      - FRIENDLY_NAME=${FRIENDLY_NAME:-UpnpRenderer}
      - RENDERER_MODE=${RENDERER_MODE:-BOTH}
      - CHECK_CONTENT_FORMAT=${CHECK_CONTENT_FORMAT:-no}
    volumes:
      - upmpdcli-confdir:/uprcl/confdir
      - upmpdcli-cache:/cache
    restart: unless-stopped

  yams:
    image: ${DOCKER_REGISTRY:-docker.io}/giof71/yams:${YAMS_TAG:-latest}
    container_name: upnp-renderer-simple-yams
    network_mode: host
    environment:
      - TZ=Europe/Rome
      - MPD_HOST=localhost
      - MPD_PORT=${MPD_PORT:-6600}
    volumes:
      - yams-data:/data
    restart: always
