---
version: "3"

services:
  upmpdcli:
    image: giof71/upmpdcli:feature-tidal-hires-jammy-full
    container_name: upmpdcli-tidal-hires
    network_mode: host
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - PORT_OFFSET=5
      - RENDERER_MODE=NONE
      - FRIENDLY_NAME=Tidal Hires Preview (upmpdcli)
      - TIDAL_ENABLE=yes
      - TIDAL_AUDIO_QUALITY=HI_RES_LOSSLESS
      - TIDAL_DOWNLOAD_PLUGIN=yes
      - TIDAL_PLUGIN_BRANCH=tidal-hires
      - WEBSERVER_DOCUMENT_ROOT=/cache/wwwpublic
    volumes:
      - ./cache:/cache
    restart: unless-stopped
