---
version: "3"

services:
  upmpdcli:
    image: ${IMAGE_REGISTRY:-docker.io}/giof71/upmpdcli:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-upmpdcli-tidal-hires}
    network_mode: host
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - PORT_OFFSET=${PORT_OFFSET:-5}
      - RENDERER_MODE=NONE
      - FRIENDLY_NAME=${FRIENDLY_NAME:-Tidal Hires (upmpdcli)}
      - TIDAL_ENABLE=yes
      - TIDAL_AUDIO_QUALITY=${TIDAL_AUDIO_QUALITY:-HI_RES_LOSSLESS}
      - TIDAL_DOWNLOAD_PLUGIN=${TIDAL_DOWNLOAD_PLUGIN:-yes}
      - TIDAL_PLUGIN_BRANCH=${TIDAL_PLUGIN_BRANCH:-latest-tidal}
      - WEBSERVER_DOCUMENT_ROOT=/cache/wwwpublic
    volumes:
      - ./cache:/cache
    restart: unless-stopped
