---
version: '3.3'

networks:
  mpd:

volumes:
  mpd-db:
  upmpdcli-cache:
  upmpdcli-confdir:
  yams-data:

services:
  mpd:
    image: ${MPD_IMAGE_REGISTRY:-docker.io}/giof71/mpd-alsa:${MPD_TAG:-vanilla}
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    environment:
      - MPD_BIND_ADDRESS=${MPD_BIND_ADDRESS:-127.0.0.1}
      - MPD_PORT=${MPD_PORT:-6600}
      - USER_MODE=N
      - ALSA_OUTPUT_CREATE=yes
      - ALSA_OUTPUT_ENABLED=yes
      - ALSA_OUTPUT_DEVICE=${MPD_ALSA_DEVICE:-default}
      - ALSA_OUTPUT_MIXER_TYPE=${MPD_MIXER_TYPE:-software}
      - ALSA_OUTPUT_FORMAT=${MPD_ALSA_OUTPUT_FORMAT:-}
    volumes:
      - mpd-db:/db
    restart: unless-stopped

  upmpdcli:
    image: ${UPMPDCLI_IMAGE_REGISTRY:-docker.io}/giof71/upmpdcli:${UPMPDCLI_TAG:-latest-renderer}
    network_mode: host
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - MPD_HOST=${MPD_HOST:-127.0.0.1}
      - MPD_PORT=${MPD_PORT:-6600}
      - FRIENDLY_NAME=${FRIENDLY_NAME:-Audirvana}
      # Audirvana does not use OpenHome
      - RENDERER_MODE=UPNPAV
      - CHECK_CONTENT_FORMAT=${CHECK_CONTENT_FORMAT:-yes}
    volumes:
      - upmpdcli-confdir:/uprcl/confdir
      - upmpdcli-cache:/cache
    restart: unless-stopped

  yams:
    image: ${YAMS_REGISTRY:-docker.io}/${YAMS_IMAGE:-giof71/yams}:${YAMS_TAG:-latest}
    network_mode: ${YAMS_NETWORK_MODE:-host}
    environment:
      - TZ=Europe/Rome
      - MPD_HOST=${MPD_HOST:-127.0.0.1}
      - MPD_PORT=${MPD_PORT:-6600}
    volumes:
      - yams-data:/data
    restart: always
