---
version: "3"

services:
  upmpdcli:
    image: ${IMAGE_REGISTRY:-docker.io}/giof71/upmpdcli:${IMAGE_TAG:-master}
    network_mode: host
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - PORT_OFFSET=${PORT_OFFSET:-10}
      - MEDIA_SERVER_FRIENDLY_NAME=${MEDIA_SERVER_FRIENDLY_NAME:-Subsonic (upmpdcli)}
      - SUBSONIC_ENABLE=yes
      - SUBSONIC_TITLE=${SUBSONIC_TITLE:-Subsonic}
      - SUBSONIC_BASE_URL=${SUBSONIC_BASE_URL}
      - SUBSONIC_PORT=${SUBSONIC_PORT}
      - SUBSONIC_USER=${SUBSONIC_USER}
      - SUBSONIC_PASSWORD=${SUBSONIC_PASSWORD}
      - SUBSONIC_LEGACYAUTH=${SUBSONIC_LEGACYAUTH:-}
      - SUBSONIC_SERVER_SIDE_SCROBBLING=${SUBSONIC_SERVER_SIDE_SCROBBLING:-}
      - SUBSONIC_FORCE_CONNECTOR_VERSION=${SUBSONIC_FORCE_CONNECTOR_VERSION:-0.3.9}
      - SUBSONIC_DOWNLOAD_PLUGIN=${SUBSONIC_DOWNLOAD_PLUGIN:-no}
      - SUBSONIC_PLUGIN_BRANCH=${SUBSONIC_PLUGIN_BRANCH:-next-subsonic}
      - PLG_PROXY_METHOD=${PLG_PROXY_METHOD:-}
      - RENDERER_MODE=${RENDERER_MODE:-NONE}
      # UPMPD_FRIENDLY_NAME is effective only when RENDERER_MODE is set to OPENHOME or BOTH
      - UPMPD_FRIENDLY_NAME=${UPMPD_FRIENDLY_NAME:-UPnP Renderer (OpenHome)}
      # AV_FRIENDLY_NAME is effective only when RENDERER_MODE is set to UPNPAV or BOTH
      - AV_FRIENDLY_NAME=${AV_FRIENDLY_NAME:-UPnP Renderer (AV)}
      - MPD_HOST=${MPD_HOST:-localhost}
      - MPD_PORT=${MPD_PORT:-6600}
      - CHECK_CONTENT_FORMAT=${CHECK_CONTENT_FORMAT:-no}
    volumes:
      - ./cache:/cache
    restart: unless-stopped

